# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  validate_metadata:
    runs-on: ubuntu-latest
    container: geneontology/dev-base:latest
    steps:
    - uses: actions/checkout@v2
    ## No whitespace after first line.
    - name: No non-tab whitespace after first line.
      run: tail -n +2 replace_relations.tsv | perl -e 'while(<>){if(/ /){die;}}'
